### ISSUE TITLE
Request to Clarify PIO usage

### ISSUE THREAD

**Issue by AKLitman** [khoih-prog/RP2040_ISR_Servo#3]
I am using the Maker PI RP2040 board by Cytron.  This Servo Library works vey well on this board using GP12 thru GP15 and a PIO.  The Adafruit NeoPixel uses PIO0 and SM0 but this library apparently knows this and uses PIO0 with SM1 and SM2.  Can you clarify this?  I ask because I am also using the NanoConnectHcSr04 library which needs single SM to function.  The NanoConnectHcSr045 has documentation showing how to deciare a specific PIO and SM.  However, there appears to be a bug in NanoConnectHcSr04 whereby only PIO0 will work even though it shows a parameter to select PIO1.

I was able to get all these libraries to function correctly together by allowing the NeoPixel to 1st select SM0, then allowing this library to select the next 2 SM's and then defining the NanoConnectHcSr04 to use PIO0 with SM3.  So, I'd just like to know exactly which PIO and SM's this library needs.  I suspect we may see future requests for PIO usage as their popularity expands.  Thank you very much.  Austin

**Comment by khoih-prog** [comment]
Hi @AKLitman 

Thanks for your `over-trust` in and your usage of the library ;-))

The library is `dumb` (it's better this way), and gets some good **intelligence** thanks to using the functions provided by the RP2040 pico-SDK via `arduino-pico` core.

I haven't really spent much time to fully investigate the smart usage / assignment of PIOx and SMy. You can get some more info from [**hardware_pio**](https://github.com/raspberrypi/pico-sdk/tree/2062372d203b372849d573f252cf7c6dc2800c0a/src/rp2_common/hardware_pio)

So, you can trust and be safe that:

1. This library is using the PIOx and SMy assigned by the core / pico-sdk. It's not hard-coded to use any fixed PIOx / SMy
2. The remaining hardware, such as NanoConnectHcSr04 can be assigned different PIOz / SMw, provided that you or the NeoPixel+NanoConnectHcSr04-related library uses the PIO/SM-related function correctly.

As this library is using the correct functions, it's safer for you to initiate the Servo at the end, after initialting NeoPixel+NanoConnectHcSr04.

If you still have more issue, it's better to post issues on `pico-sdk`, `arduino-pico` core or the other `NeoPixel+NanoConnectHcSr04` libraries.

Good Luck,

---


> /** \file hardware/pio.h
>  *  \defgroup hardware_pio hardware_pio
>  *
>  * Programmable I/O (PIO) API
>  *
>  * A programmable input/output block (PIO) is a versatile hardware interface which
>  * can support a number of different IO standards. There are two PIO blocks in the RP2040.
>  *
>  * Each PIO is programmable in the same sense as a processor: the four state machines independently
>  * execute short, sequential programs, to manipulate GPIOs and transfer data. Unlike a general
>  * purpose processor, PIO state machines are highly specialised for IO, with a focus on determinism,
>  * precise timing, and close integration with fixed-function hardware. Each state machine is equipped
>  * with:
>  *  * Two 32-bit shift registers – either direction, any shift count
>  *  * Two 32-bit scratch registers
>  *  * 4×32 bit bus FIFO in each direction (TX/RX), reconfigurable as 8×32 in a single direction
>  *  * Fractional clock divider (16 integer, 8 fractional bits)
>  *  * Flexible GPIO mapping
>  *  * DMA interface, sustained throughput up to 1 word per clock from system DMA
>  *  * IRQ flag set/clear/status
>  *
>  * Full details of the PIO can be found in the RP2040 datasheet.
>  */

**Comment by khoih-prog** [comment]
The correct function to use to get free PIO/SM is

`servoPgm.prepare(&pio, &smIdx, &pgmOffset)`

as in

```
if (!_servoPgm.prepare(&servo[servoIndex].pio, &servo[servoIndex].smIdx, &servo[servoIndex].pgmOffset)) 
{
  // ERROR, no free slots
  ISR_SERVO_LOGERROR("Error no free slot");
  return -1;
}
```

You can check if those libraries are using the same `smart` function.

**Comment by AKLitman** [comment]
Thank you very much.  I have much to learn about these functions.  Thank you for pointing me in the correct direction and for writing your library in the Approved manner for automatic PIO & SM assignment.

**Comment by AKLitman** [comment]
Dear khoih-prog, the Author of the Sonar Ping library (NanoConnectHcSr04) has replied and pointed to a couple lines in his code where he hardcoded the PIO instead of using the values the User is asked to supply.  I altered the library on my own system and the Sonar Ping now allows me yo specify any of the PIO's and corresponding SM's.  I remain hopeful he will publish a new version with these changes and that eventually he will re-write his library to follow the SDK guidelines and make his library truly universal in function.  You, Sir, are following the "best practices" of coding and I hold you in high esteem.  Austin

**Comment by khoih-prog** [comment]
Can you post the link to that library. Thanks.

**Comment by khoih-prog** [comment]
It's also better to use auto-assigned values from the pico-sdk / core. Not good to assign them yourself.  More issues will come later if you're manually doing so.

**Comment by AKLitman** [comment]
https://github.com/MrYsLab/NanoConnectHcSr04 is the library for the Sonar Ping.  While it was intended for the HC-SR04 module, I am using it with the US-100 module and it works perfectly.  I fully agree that having hardcoded PIO's is not optimal, I am not skilled enough to take on this task myself.  Perhaps as my knowledge and confidence grows, I might be able to complete such a task in the future but I am not competent to try it now.

**Comment by khoih-prog** [comment]
Just try and I'll help you to spot any possible mistake. We together can learn lot of things via the exercise.

**Comment by AKLitman** [comment]
Dear khoih-prog, The Author of NanoConnectHcSr04 has released a new version which corrects the hard coding error the prior version had.  With several variations of PIO & SM, I tested both his Example and my code incorporating his library and both function correctly.  I mentioned where he might find the auto-assign of PIO & SM functions which he apparently looked at but he doesn't feel it is complete.  At the risk of violating some authorship protocols, here is a part of his reply to me.

"For the auto-select feature, it appears the SDK can only find an available SM for a given pio (pio_claim_unused_sm). Unless I missed something, it does not do an autoselect for both sm and pio. If the claim fails for both pio's, I am unsure what to do about it. If this repo is used in conjunction with [telemetrix-nano-2040-wifi](https://github.com/MrYsLab/telemetrix-nano-2040-wifi), I could send an error report back that would result in an exception being thrown on the Python side. However, if the repo is being used in a standalone fashion, I am not sure how to handle the failure. Not every user has a serial port connected to the board. I am open to any suggestions you might have."
