### ISSUE TITLE
Permit using servos with different pulse ranges simultaneously

### ISSUE THREAD

**Issue by Samt43** [khoih-prog/RP2040_ISR_Servo#5]
Setup 2 servos with 2 differents ranges.
Set a position on the first servo you have setup, the pulse range used by the lib is not correct, and this result in a bad positionning.

Arduino IDE version: 1.8.19
RP2040_ISR_Servo 1.1.1

**Comment by khoih-prog** [comment]
Closed #5 via PR #4

**Comment by Samt43** [comment]
Thanks !!
